# Generated by Django 5.0.6 on 2024-05-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app__foodie", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
