# Generated by Django 5.0.6 on 2024-05-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app__foodie", "0003_recipe"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Recipe",
        ),
    ]
