# Generated by Django 5.0.6 on 2024-05-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app__recipe", "0002_recipe_user_alter_recipe_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="recipe_images/"),
        ),
    ]
