# Generated by Django 5.0.6 on 2024-05-19 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app__sandbox", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="feeback",
            new_name="feedback",
        ),
    ]
